# Generated by Django 5.2.7 on 2025-11-21 02:07

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_type', models.CharField(choices=[('WINTER', 'Winter Tires'), ('ALL_SEASON', 'All Season Tires')], max_length=20)),
                ('rim_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(24)])),
                ('size', models.CharField(max_length=50)),
                ('load_speed', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=50)),
                ('tread_pattern', models.CharField(max_length=50)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('set_of_tire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('environmental_fee', models.DecimalField(decimal_places=2, default=4.5, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('install_included', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stocked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tire_type', 'rim_size', 'size'],
            },
        ),
        migrations.CreateModel(
            name='TireImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to=api.models.tire_image_upload_path)),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.tire')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
